# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=30, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMateria', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('cupos', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=10, unique=True)),
                ('idCA', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administrador.Alumno')),
            ],
        ),
    ]
