# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_remove_materia_idca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='descripcion',
            field=models.TextField(default='descripcion', max_length=50),
        ),
    ]
